[package]
name = "zerolink"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.15.0"

[dependencies]
starknet = "2.15.0"
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v1.0.0" }
openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v1.0.0" }

[[target.starknet-contract]]
sierra = true
casm = true
